/**
 * Step 2 of the validation pipeline.
 *
 * Produces every generated artifact of each style package in `PACKAGES`:
 *
 *   1. The three interoperability formats, produced by *actually running* the
 *      official `design.md export` CLI, stored verbatim:
 *        <package>/tokens/tokens.json        (--format dtcg)
 *        <package>/dist/tokens.css           (--format css-vars)
 *        <package>/dist/tailwind.theme.json  (--format json-tailwind)
 *
 *   2. A lossless companion derivation of the same contract, used by the
 *      reference pages and by any consumer that needs values no official export
 *      emits. Verified against DESIGN.md v0.4.0:
 *        - no official export emits the component token table (61 entries), nor
 *          the `fontFeature` setting on the two tabular roles;
 *        - `--format css-vars` emits only colours, spacing and radii (48
 *          properties) — it omits typography entirely;
 *      so the companion carries the whole contract, flattened into one CSS
 *      custom-property namespace and one JSON document:
 *        <package>/dist/tokens.full.css
 *        <package>/dist/tokens.full.json
 *
 *      The limitation list above is re-checked on every run by
 *      `npm run 3:verify-generated`, so this header cannot go stale silently.
 *
 * Run: npm run 2:export
 */

import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import path from 'node:path';

import {
  REPO_ROOT,
  packagePaths,
  loadContract,
  requestedPackages,
  assertNoErrors,
  cssCustomProperties,
  fullJson,
} from './lib/design-system.mjs';

const DESIGN_MD_BIN = path.join(
  REPO_ROOT,
  'node_modules',
  '@google',
  'design.md',
  'dist',
  'index.js',
);

/** The three official export formats, paired with the artifact each one fills. */
const formatsFor = (artifacts) => [
  ['dtcg', artifacts.dtcg],
  ['css-vars', artifacts.cssVars],
  ['json-tailwind', artifacts.tailwind],
];

function runOfficialExport(format, contractPath) {
  return new Promise((resolve, reject) => {
    const child = spawn(
      process.execPath,
      [DESIGN_MD_BIN, 'export', contractPath, '--format', format],
      { cwd: REPO_ROOT },
    );
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => (stdout += d));
    child.stderr.on('data', (d) => (stderr += d));
    child.on('error', reject);
    child.on('close', (code) => {
      if (code !== 0) {
        reject(
          new Error(
            `design.md export --format ${format} exited with ${code}\n${stderr}`,
          ),
        );
      } else {
        resolve(stdout);
      }
    });
  });
}

function cssHeader(sha, pkg, lines) {
  return [
    '/*',
    ` * ${pkg} — generated file. Do not edit by hand.`,
    ' *',
    ` * Source of truth : ${pkg}/DESIGN.md`,
    ` * Source sha256   : ${sha}`,
    ' * Generated by    : scripts/export-tokens.mjs (npm run 2:export)',
    ` * Contains        : ${lines}`,
    ' */',
    '',
  ].join('\n');
}

async function main() {
  const packages = requestedPackages();

  for (const [index, pkg] of packages.entries()) {
    if (index > 0) console.log('');
    const { contract, artifacts } = packagePaths(pkg);
    const formats = formatsFor(artifacts);

    const { raw, report } = await loadContract(pkg);
    assertNoErrors(report, `${pkg}/DESIGN.md`);
    const sha = createHash('sha256').update(raw, 'utf8').digest('hex');

    // 1. official exports, verbatim.
    for (const [format, outPath] of formats) {
      const text = await runOfficialExport(format, contract);
      await mkdir(path.dirname(outPath), { recursive: true });
      await writeFile(outPath, text, 'utf8');
      console.log(`official  ${path.relative(REPO_ROOT, outPath)}  (${format})`);
    }

    // 2. lossless companion derivation.
    const state = report.designSystem;
    const props = cssCustomProperties(state);

    const body = props
      .map(([name, value]) => `  ${name}: ${value};`)
      .join('\n');
    const fullCss =
      cssHeader(
        sha,
        pkg,
        'colours, typography (with line-height and font-feature), spacing, radii, and the 61 component tokens — the complete contract',
      ) + `:root {\n${body}\n}\n`;
    await writeFile(artifacts.fullCss, fullCss, 'utf8');
    console.log(
      `derived   ${path.relative(REPO_ROOT, artifacts.fullCss)}  (${props.length} custom properties)`,
    );

    const json = fullJson(state, {
      contractPath: `${pkg}/DESIGN.md`,
      contractSha256: sha,
      generator: 'scripts/export-tokens.mjs',
    });
    await writeFile(artifacts.fullJson, `${JSON.stringify(json, null, 2)}\n`, 'utf8');
    console.log(
      `derived   ${path.relative(REPO_ROOT, artifacts.fullJson)}  ` +
        `(${Object.keys(json.colors).length} colours, ${Object.keys(json.typography).length} typography roles, ` +
        `${Object.keys(json.spacing).length} spacing, ${Object.keys(json.rounded).length} radii, ` +
        `${Object.keys(json.components).length} components)`,
    );

    console.log(
      `\ncontract  ${pkg}/DESIGN.md  sha256 ${sha.slice(0, 16)}…  ` +
        `lint: ${report.summary.errors} errors / ${report.summary.warnings} warnings`,
    );

    // Fail loudly if an official export silently produced nothing.
    for (const [, outPath] of formats) {
      const text = await readFile(outPath, 'utf8');
      if (text.trim().length === 0) {
        throw new Error(`official export produced an empty file: ${outPath}`);
      }
    }
  }
}

main().catch((err) => {
  console.error(`\nexport-tokens failed: ${err.message}`);
  process.exit(1);
});
